# See https://github.com/silverstripe/silverstripe-travis-support for setup details

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

dist: precise

env:
  - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3 COVERAGE="--coverage-clover=coverage.xml"

before_script:
  - echo -e "[server]\nmax_allowed_packet=64M" | sudo tee -a /etc/mysql/conf.d/dms.cnf
  - sudo service mysql restart
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/build/ss --require undefinedoffset/sortablegridfield:~0.6.9
  - cd ~/build/ss
  - composer install

script:
  - vendor/bin/phpunit "$COVERAGE" dms/tests

after_success:
  - >
    test "$COVERAGE" != ""
    && mv coverage.xml ~/build/$TRAVIS_REPO_SLUG
    && cd ~/build/$TRAVIS_REPO_SLUG
    && bash <(curl -s https://codecov.io/bash)
